export const AIRPORT_CITIES: Record<string, string> = {
    DOH: 'Doha',
    BUD: 'Budapest',
    FRA: 'Frankfurt',
    HAM: 'Hamburg',
    SVO: 'Moscow',
    MAD: 'Madrid',
    GOX: 'Goa',
    CPT: 'Cape Town',
    DPS: 'Bali',
    LHR: 'London',
    DXB: 'Dubai',
    RUH: 'Riyadh',
    CAI: 'Cairo',
    AKL: 'Auckland',
    DUB: 'Dublin',
    ARN: 'Stockholm',
    LHE: 'Lahore',
    WAW: 'Warsaw',
    DEL: 'Delhi',
    YUL: 'Montreal',
    MUC: 'Munich',
    TUN: 'Tunis',
    KUL: 'Kuala Lumpur',
    BNE: 'Brisbane',
    BER: 'Berlin',
    MLE: 'Male',
    CKG: 'Chongqing',
    ATL: 'Atlanta',
    AUH: 'Abu Dhabi',
    CMB: 'Colombo',
    DAC: 'Dhaka',
    JED: 'Jeddah',
    CGK: 'Jakarta',
    ICN: 'Seoul',
    MIA: 'Miami',
    DFW: 'Dallas',
    CCU: 'Kolkata',
};

export const AIRPORT_COORDINATES: Record<string, { latitude: number; longitude: number }> = {
    DOH: { latitude: 25.2731, longitude: 51.6081 },
    BUD: { latitude: 47.4369, longitude: 19.2556 },
    FRA: { latitude: 50.0333, longitude: 8.5706 },
    HAM: { latitude: 53.6304, longitude: 9.9882 },
    SVO: { latitude: 55.9725, longitude: 37.4146 },
    MAD: { latitude: 40.4719, longitude: -3.5626 },
    GOX: { latitude: 15.7667, longitude: 73.8667 },
    CPT: { latitude: -33.9648, longitude: 18.6017 },
    DPS: { latitude: -8.7481, longitude: 115.1672 },
    LHR: { latitude: 51.4706, longitude: -0.4619 },
    DXB: { latitude: 25.2528, longitude: 55.3644 },
    RUH: { latitude: 24.9576, longitude: 46.6988 },
    CAI: { latitude: 30.1219, longitude: 31.4056 },
    AKL: { latitude: -37.0080, longitude: 174.7920 },
    DUB: { latitude: 53.4213, longitude: -6.2701 },
    ARN: { latitude: 59.6519, longitude: 17.9186 },
    LHE: { latitude: 31.5216, longitude: 74.4036 },
    WAW: { latitude: 52.1657, longitude: 20.9671 },
    DEL: { latitude: 28.5562, longitude: 77.1000 },
    YUL: { latitude: 45.4706, longitude: -73.7408 },
    MUC: { latitude: 48.3538, longitude: 11.7861 },
    TUN: { latitude: 36.8510, longitude: 10.2272 },
    KUL: { latitude: 2.7456, longitude: 101.7097 },
    BNE: { latitude: -27.3856, longitude: 153.1175 },
    BER: { latitude: 52.3667, longitude: 13.5033 },
    MLE: { latitude: 4.1918, longitude: 73.5291 },
    CKG: { latitude: 29.7197, longitude: 106.6436 },
    ATL: { latitude: 33.6407, longitude: -84.4277 },
    AUH: { latitude: 24.4330, longitude: 54.6511 },
    CMB: { latitude: 7.1802, longitude: 79.8853 },
    DAC: { latitude: 23.8433, longitude: 90.4054 },
    JED: { latitude: 21.6796, longitude: 39.1565 },
};

export const AIRPORT_ICAO: Record<string, string> = {
    DOH: 'OTHH',
    BUD: 'LHBP',
    FRA: 'EDDF',
    HAM: 'EDDH',
    SVO: 'UUEE',
    MAD: 'LEMD',
    GOX: 'VAGO',
    CPT: 'FACT',
    DPS: 'WADD',
    LHR: 'EGLL',
    DXB: 'OMDB',
    RUH: 'OERK',
    CAI: 'HECA',
    AKL: 'NZAA',
    DUB: 'EIDW',
    ARN: 'ESSA',
    LHE: 'OPLA',
    WAW: 'EPWA',
    DEL: 'VIDP',
    YUL: 'CYUL',
    MUC: 'EDDM',
    TUN: 'DTTA',
    KUL: 'WMKK',
    BNE: 'YBBN',
    BER: 'EDDB',
    MLE: 'VRMM',
    CKG: 'ZUCK',
    ATL: 'KATL',
    AUH: 'OMAA',
    CMB: 'VCBI',
    DAC: 'VGHS',
    JED: 'OEJN',
};

export const AIRPORT_INFO: Record<string, { description: string; images: any[] }> = {
    CKG: {
        description: "Chongqing Jiangbei International Airport is the primary airport serving Chongqing, China. It is a major hub for western China and features modern facilities across three terminals.",
        images: [
            require('../assets/images/airports/ckg1.jpeg'),
            require('../assets/images/airports/ckg2.jpg'),
        ]
    },
    DOH: {
        description: "Hamad International Airport is the international airport for Doha, the capital city of Qatar. It is known for its architecture and is a global hub for Qatar Airways.",
        images: []
    }
};
